repos:
  -    repo: git@github.com:psf/black.git
       rev: 26.1.0
       hooks:
         - id: black
           args: [--line-length=100, --skip-string-normalization]
  -    repo: https://github.com/pycqa/flake8
       rev: 7.3.0
       hooks:
         - id: flake8
           args: [ '--config=setup.cfg']
           additional_dependencies: [ flake8-bugbear, flake8-eradicate, pep8-naming, dlint ]

  -    repo: https://github.com/pre-commit/pre-commit-hooks
       rev: v6.0.0
       hooks:
       - id: double-quote-string-fixer
       - id: check-json
       - id: check-ast
       - id: check-yaml
         args: ['--unsafe']
       - id: detect-private-key
  -    repo: https://github.com/asottile/pyupgrade
       rev: v3.21.2
       hooks:
         - id: pyupgrade
  -    repo: https://github.com/pre-commit/mirrors-isort
       rev: v5.10.1
       hooks:
         - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args: [--follow-imports=silent, --ignore-missing-imports]
        exclude: "tests/.+"
        additional_dependencies: ['types-python-dateutil', 'types-aiofiles']
