apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "typewiki-airflow.fullname" . }}
  labels: {{ include "typewiki-airflow.labels" . | nindent 4 }}
data:
  OPENAI_EMBEDDING_MODEL_NAME: {{ .Values.config.openaiEmbeddingModelName | quote }}
  PINECONE_INDEX_NAME: {{ .Values.config.pineconeIndexName | quote }}
  TYPEWIKI_PDF_DIR: {{ .Values.config.pdfDir | quote }}
  AIRFLOW_HOME: {{ .Values.config.airflowHome | quote }}
