apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "typewiki-api.fullname" . }}
  labels: {{ include "typewiki-api.labels" . | nindent 4 }}
data:
  OPENAI_MODEL_NAME: {{ .Values.config.openaiModelName | quote }}
  OPENAI_EMBEDDING_MODEL_NAME: {{ .Values.config.openaiEmbeddingModelName | quote }}
  PINECONE_INDEX_NAME: {{ .Values.config.pineconeIndexName | quote }}
  HTTP_CLIENT_TIMEOUT_SECONDS: {{ .Values.config.httpClientTimeoutSeconds | quote }}
